services:
  traefik:
    image: traefik:v3.7
    container_name: cloudy_traefik
    user: "0:0"
    security_opt:
      - label=disable
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres:
    image: postgres:17
    container_name: cloudy_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ktor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ACOUSTID_API_KEY: ${ACOUSTID_API_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      DB_DRIVER: ${DB_DRIVER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      TOTAL_SPACE_PER_FOLDER: ${TOTAL_SPACE_PER_FOLDER}
    volumes:
      - ./app_docker_data:/app:z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloudy.rule=Host(`cloudy.localhost`)"
      - "traefik.http.routers.cloudy.entrypoints=web"
      - "traefik.http.services.cloudy.loadbalancer.server.port=${PORT}"

volumes:
  postgres_data: