services:
  ktor:
    image: cloudy-docker-image:0.0.8
    restart: always
    ports:
      - "10.7.147.212:8080:8080"
    environment:
      ACOUSTID_API_KEY: "b'CHjabLfl"
      AUTH_SECRET: "SECRET"
      HOST: "10.109.139.243"
      PORT: "8080"
      DB_URL: "jdbc:sqlite:cloudyDB.db?foreign_keys=on"
      DB_DRIVER: "org.sqlite.JDBC"
