apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  auth: "SECRET"
  host: "0.0.0.0"
  port: "8080"

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
