apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-volume-claim
  labels:
    app: api
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi