apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-volume
  labels:
    type: local
    app: api
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/musics