tls:
  certificates:
    - certFile: /certs/local.crt
      keyFile: /certs/local.key

http:
  routers:
    api:
      rule: "Host(`cloudy.localhost`)"
      entryPoints:
        - websecure
      service: api-service
      tls: {}

    api-http:
      rule: "Host(`cloudy.localhost`)"
      entryPoints:
        - web
      service: api-service

  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://ktor:8080"